version: "3.9"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    environment:
      - LANG=de
      - WG_HOST=leojay.synology.me
      - PASSWORD=leojay@20240131make
      - WG_DEVICE=eth-wg0
      - WG_DEFAULT_ADDRESS=10.8.1.0
      - WG_DEFAULT_DNS=10.3.3.x
    cap-add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
