version: '3.4'

services:
  nginx:
    image: nginx:1.21.6
    # restart: on-failure
    restart: always
    ports: 
      - "9091:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docsify:/web
      