version: '3.4'

services:
  nginx-docsify:
    image: hub.leojay.site/dhub/nginx:1.27.0
    restart: always
    ports: 
      - "3001:80"
      # - "9443:443"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../docsify:/web
      #- ../volume/nginx/cert:/cert
  # node-docsify:
  #   build: 
  #     # dockerfile: dockerfile-nodejs
  #     dockerfile: dockerfile
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #     - "35729:35729"
  #   volumes:
  #     - ../docsify:/docs

    
      