services:
  nginx-docsify:
    image: hub.leojay.site/dhub/nginx:1.27.0
    restart: always
    ports: 
      - "3001:80"
      # - "9443:443"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../docs:/web/www
      #- ../volume/nginx/cert:/cert

  node-docsify:
    build: 
      context: node
      # dockerfile: dockerfile-nodejs
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ../docs:/docs

    
      